apiVersion: v1
kind: Service
metadata:
  labels:
    app: httpd
    name: httpd
  name: httpd
spec:
  ports:
  - name: httpd
    port: 8080
    protocol: TCP
    targetPort: 8081
  selector:
    name: httpd
